[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"

[deploy]
startCommand = "set -e; echo '[boot] migrate'; python manage.py migrate --noinput; echo '[boot] collectstatic'; python manage.py collectstatic --noinput; echo '[boot] init_superuser'; python manage.py init_superuser; echo \"[boot] starting gunicorn on port=$PORT\"; exec gunicorn querygrade.wsgi --log-file - --log-level info --bind 0.0.0.0:$PORT"
