[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"

[deploy]
preDeployCommand = "sh -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py init_superuser'"
startCommand = "sh -c 'gunicorn querygrade.wsgi --log-file - --log-level info --bind 0.0.0.0:$PORT'"
