# Generated by Django 4.2.24 on 2025-09-27 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable model name', max_length=100)),
                ('model_type', models.CharField(choices=[('QUERY_GRADER', 'Query Grader'), ('FEATURE_EXTRACTOR', 'Feature Extractor'), ('FEEDBACK_PREDICTOR', 'Feedback Predictor'), ('HYBRID_SCORER', 'Hybrid Scorer')], max_length=20)),
                ('version', models.CharField(help_text="Model version (e.g., '1.0.0')", max_length=20)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('ARCHIVED', 'Archived')], default='TRAINING', max_length=12)),
                ('file_path', models.CharField(help_text='Path to the model file', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(help_text='SHA256 checksum of model file', max_length=64)),
                ('training_accuracy', models.FloatField(blank=True, help_text='Training accuracy (0-1)', null=True)),
                ('validation_accuracy', models.FloatField(blank=True, help_text='Validation accuracy (0-1)', null=True)),
                ('training_samples', models.IntegerField(default=0, help_text='Number of training samples used')),
                ('training_time_seconds', models.IntegerField(default=0, help_text='Training time in seconds')),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_predictions', models.BigIntegerField(default=0)),
                ('average_prediction_time_ms', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(help_text='Model accuracy (0-1)')),
                ('precision', models.FloatField(help_text='Model precision (0-1)')),
                ('recall', models.FloatField(help_text='Model recall (0-1)')),
                ('f1_score', models.FloatField(help_text='F1 score (0-1)')),
                ('user_agreement_rate', models.FloatField(help_text='Rate of user agreement with predictions (0-1)')),
                ('avg_user_rating', models.FloatField(help_text='Average user rating for model predictions (1-5)')),
                ('prediction_count', models.IntegerField(default=0, help_text='Number of predictions made')),
                ('avg_prediction_time_ms', models.FloatField(help_text='Average prediction time in milliseconds')),
                ('error_rate', models.FloatField(default=0.0, help_text='Error rate (0-1)')),
                ('measurement_period_start', models.DateTimeField()),
                ('measurement_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analyzer.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_grade', models.CharField(max_length=1)),
                ('original_score', models.FloatField()),
                ('original_confidence', models.FloatField(default=0.5, help_text='Model confidence (0-1)')),
                ('feedback_grade_equivalent', models.FloatField(help_text='User feedback converted to grade scale (0-100)')),
                ('grade_difference', models.FloatField(help_text='Difference between user and system grade')),
                ('feedback_weight', models.FloatField(default=1.0, help_text='Weight of this feedback for learning')),
                ('was_used_for_training', models.BooleanField(default=False)),
                ('training_session', models.CharField(blank=True, help_text='ID of training session that used this feedback', max_length=50)),
                ('user_reliability_score', models.FloatField(default=0.5, help_text='Reliability score of the user providing feedback')),
                ('context_similarity_score', models.FloatField(default=0.0, help_text='Similarity to other queries in training set')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_data', to='analyzer.userqueryhistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grade_avg', models.FloatField(help_text='Average grade from user feedback (1-5 scale)')),
                ('user_grade_count', models.IntegerField(default=0, help_text='Number of user ratings')),
                ('user_grade_stddev', models.FloatField(default=0.0, help_text='Standard deviation of user ratings')),
                ('system_grade', models.CharField(help_text='Original system grade (A-F)', max_length=1)),
                ('system_score', models.FloatField(help_text='Original system score (0-100)')),
                ('accuracy_rating_avg', models.FloatField(blank=True, null=True)),
                ('usefulness_rating_avg', models.FloatField(blank=True, null=True)),
                ('clarity_rating_avg', models.FloatField(blank=True, null=True)),
                ('database_type', models.CharField(blank=True, max_length=50)),
                ('query_complexity', models.IntegerField(default=0)),
                ('table_count', models.IntegerField(default=0)),
                ('join_count', models.IntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this sample has been validated')),
                ('validation_source', models.CharField(blank=True, help_text='Source of validation (manual, benchmark, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to='analyzer.query')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['query', 'is_validated'], name='analyzer_tr_query_i_abefaa_idx'), models.Index(fields=['database_type'], name='analyzer_tr_databas_c641ad_idx'), models.Index(fields=['user_grade_count'], name='analyzer_tr_user_gr_6d5983_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', 'status'], name='analyzer_ml_model_t_7ea570_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['version'], name='analyzer_ml_version_6584da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('model_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='learningmetrics',
            index=models.Index(fields=['model', '-created_at'], name='analyzer_le_model_i_3a591c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmetrics',
            index=models.Index(fields=['measurement_period_start'], name='analyzer_le_measure_abe2df_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklearning',
            index=models.Index(fields=['was_used_for_training'], name='analyzer_fe_was_use_eaef5f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklearning',
            index=models.Index(fields=['feedback_weight'], name='analyzer_fe_feedbac_4c4c76_idx'),
        ),
    ]
