# Generated by Django 5.2.7 on 2026-05-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_mlmodel_learningmetrics_feedbacklearning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdata",
            name="features_json",
            field=models.JSONField(
                blank=True,
                help_text="41-dim feature vector extracted from query",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="feedback_weight",
            field=models.FloatField(
                default=1.0, help_text="Sample importance weight for training"
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="target_score",
            field=models.FloatField(
                blank=True, help_text="Target score for training (0-100)", null=True
            ),
        ),
    ]
