# Generated by Django 5.2.7 on 2026-05-07 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_trainingdata_ml_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly label, e.g. 'staging-orders'",
                        max_length=100,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlite", "SQLite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(blank=True, default="localhost", max_length=255),
                ),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "db_name",
                    models.CharField(
                        help_text="Database name, or absolute file path for SQLite",
                        max_length=255,
                    ),
                ),
                ("db_user", models.CharField(blank=True, default="", max_length=100)),
                ("password_encrypted", models.TextField(blank=True, default="")),
                (
                    "schema",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PostgreSQL schema; ignored for MySQL/SQLite",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_used_at"],
                        name="analyzer_us_user_id_36c16b_idx",
                    )
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
