# Generated by Django 5.2.7 on 2026-05-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0004_userdatabaseconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryanalysis",
            name="index_recommendations",
            field=models.JSONField(
                blank=True, default=dict, help_text="Schema-aware index recommendations"
            ),
        ),
    ]
