# Generated by Django 5.2.7 on 2026-05-17 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0005_queryanalysis_index_recommendations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("DRIFT", "Concept drift"),
                            ("DATA_DRIFT", "Data drift"),
                            ("PERFORMANCE", "Performance degradation"),
                            ("CONFIDENCE", "Low confidence"),
                            ("USER_AGREEMENT", "User-agreement drop"),
                            ("TIME_BASED", "Time-based retrain"),
                            ("ROLLBACK_PERFORMED", "Rollback performed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False positive"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="analyzer.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "-created_at"],
                        name="analyzer_ml_model_i_80e157_idx",
                    ),
                    models.Index(
                        fields=["status", "severity"],
                        name="analyzer_ml_status_f28f37_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="analyzer_ml_created_4fc4da_idx"
                    ),
                    models.Index(
                        fields=["alert_type", "status"],
                        name="analyzer_ml_alert_t_73b188_idx",
                    ),
                ],
            },
        ),
    ]
