# Generated by Django 5.2.7 on 2026-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_mlalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryanalysis",
            name="schema_insights",
            field=models.JSONField(
                blank=True, default=dict, help_text="Schema-aware non-index insights"
            ),
        ),
    ]
