# Generated by Django 4.2.30 on 2026-07-18 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_queryanalysis_schema_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(help_text='joblib-serialized model bytes')),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 of the stored bytes', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='analyzer.mlmodel')),
            ],
        ),
    ]
